### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Abyss777** [traccar/traccar#2308]
I want to collect feature requests in this issue.
Also I think to do it in separate messages and people can "vote" for them using github "add your reaction"
@tananaev is it OK?

**Comment by tananaev** [comment]
Yes, that would be great.

**Comment by Abyss777** [comment]
- [ ] Aliases for position attributes #2302

**Comment by Abyss777** [comment]
- [ ] Draw route of trip on click #2309

**Comment by Abyss777** [comment]
- [ ] Show events on map #2310

**Comment by Abyss777** [comment]
- [ ] Draw the device route (LIVE) #2008

**Comment by Abyss777** [comment]
- [ ] New role - manager #1835

**Comment by Abyss777** [comment]
- [ ] Traccar Monitoring Integrated #985

**Comment by Abyss777** [comment]
- [ ] Group Snapshot / Replay #2053

**Comment by Abyss777** [comment]
- [ ] Some kind of delayed event notifications #2189

**Comment by Abyss777** [comment]
- [ ] Timeline #1546

**Comment by Abyss777** [comment]
- [ ] Always show geofences on map #2156

**Comment by Gar-za** [comment]
A nice feature would be a to make a geofence around one of the units therefore making a moving geofence.  

This would be ideal in a situation where you are delivering something to a work crew that moves all day.

**Comment by Abyss777** [comment]
- [ ] Allow set "user"/"user list" who to alert for a particular device #2061

**Comment by Abyss777** [comment]
- [ ] Export reports to PDF #1545

**Comment by tananaev** [comment]
- [ ] Playback function #115

**Comment by tananaev** [comment]
- [ ] Add own POI and pics of the cars #513

**Comment by tananaev** [comment]
We can also take a look at requests for old web interface:

https://github.com/tananaev/traccar-web/issues

There are quite a few there. Some might be duplicates though.

**Comment by akmal1999** [comment]
what do you think of Adding KML file export of the maps to be imported in google maps

**Comment by akmal1999** [comment]
what do you think of gas and engine status feedback?

**Comment by akmal1999** [comment]
what about a dashboard for reporting purposes where we will collect reporting based on driver behaviour, speed control, start and stop status... and so on.

**Comment by tananaev** [comment]
@akmal1999, I would recommend to create a separate issue for each feature that you want to see. Because if we start to discuss everything here, it will become a mess very quickly. This thread is just to keep track of everything so we can plan next release.

**Comment by Abyss777** [comment]
- [ ] Extend web interface to handle direct links on device/position/event #2312

**Comment by Abyss777** [comment]
- [ ] Embedded public view #2313

**Comment by nefertiti007** [comment]
- [ ] Device Management Related Info #2316

**Comment by nefertiti007** [comment]
- [ ] Position : Sticky attributes Values #2325

**Comment by akmal1999** [comment]
Hi,

Do we have a feature figured out for KML download that could be used for google earth?  currently we only have csv and not kml... is it possible?

**Comment by tananaev** [comment]
@akmal1999, please don't comment on this thread. You've already created a separate thread for KML export. If you want to ask something, ask it there.

**Comment by MikeRD03** [comment]
I would request a GPX export feature for routes

**Comment by CitizenZero8** [comment]
I think it will be great if could send all config messages to gps tracker unit with SMS panel.
Also adding a date type converter to web interface and apps will be a useful feature.

**Comment by jenellej** [comment]
I think being able to send commands to devices via sms would be a great feature. Traccar could use an API of something like https://play.google.com/store/apps/details?id=networked.solutions.sms.gateway.api installed on an android phone to send the messages.

**Comment by barikinboxru** [comment]
adjust the distance traveled (distance traveled calculation for GT02A type devices TK110). For those devices that do not consider yourself the distance traveled. The problem described on the forum topic: "Not calculates the distance traveled"

**Comment by cristianormoraes** [comment]
Location search box in geofence area window. 
It would be easier to search the street to add the area.

**Comment by rnsalmorin** [comment]
A notification of devices in idle mode (0kph) outside GEOFENCE equivalent to 30minutes or up.
No alarm when inside geofence.
Applicable to us since our units are point to point from arrival and to destination. Not allowing units to standby.

**Comment by tananaev** [comment]
Please stop adding descriptions directly to this thread. It makes it impossible to discuss your ideas and therefore less likely to be implemented. Instead create a separate thread and link it here with a short description.

**Comment by peteclyde** [comment]
A test email / notification option - I'm playing with email settings and to test them out I need to force an event of some sort.

**Comment by Neoespecialistas** [comment]
Reset the TotalDistance value
See: https://www.traccar.org/forums/topic/totaldistance-tip/

**Comment by tananaev** [comment]
@Neoespecialistas, it's already implemented in version 3.8.

**Comment by jaimzj** [comment]
- [ ] #2393

**Comment by masfranzhuo** [comment]
an idle condition, such as when unit not moving for 5 minutes we called it event: idle start, then after unit move we got event: idle end

**Comment by tananaev** [comment]
@masfranzhuo, you need to create a separate thread for your feature request. Also, you would need to explain use case and how it's different from movement alert now.

**Comment by greatidea1** [comment]
Adding security to /api/server endpoint [#4204](https://github.com/traccar/traccar/issues/4204)

**Comment by greatidea1** [comment]
Adding Snap-to-Road feature [#4205](https://github.com/traccar/traccar/issues/4205)

**Comment by Artiom-M** [comment]
- [ ] Show management device's location on the map https://github.com/traccar/traccar-web/issues/816

**Comment by tananaev** [comment]
Closing this. If some features are still missing and you're interested in them, please create separate tickets.

**Comment by jsnxptech** [comment]
Add device location sharing function - [https://github.com/traccar/traccar/issues/5025](url)

**Comment by tananaev** [comment]
Please learn how to share links on GitHub. Also, this is a closed ticket. Please don't comment on closed tickets except if there's some regression.

**Comment by jsnxptech** [comment]
> Aprenda como compartilhar links no GitHub. Além disso, este é um ticket fechado. Por favor, não comente sobre tickets fechados, exceto se houver alguma regressão.

então onde ´podemos fazer tal Solicitação?
